# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [19]:
planet = "Earth"
diameter = 12742

In [21]:
var="{s4}{s3}{s2}{s1}".format(s1= '12742 kilometers' ,s2= 'Earth is' ,s3= 'diameter of' ,s4='The')
print(var)

Thediameter ofEarth is12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [22]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

# Numpy

In [29]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [31]:
array=np.zeros(10)
print("An array of 10 zeros")
print(array)

An array of 10 zeros
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [32]:
array=np.ones(10)*5
print("An array of 10 fives")
print(array)

An array of 10 fives
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [33]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 20 to 35")
print(array)


Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [36]:
import numpy as np
x=  np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]




## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [38]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b),axis=0)


array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [25]:
import pandas as pd


In [28]:
series=pd.Series([1,2,3])

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [41]:
import pandas as pd
per1=pd.date_range(start='1-1-2023',end='10-2-2023',freq='M')
for val in per1:
  print(val)


2023-01-31 00:00:00
2023-02-28 00:00:00
2023-03-31 00:00:00
2023-04-30 00:00:00
2023-05-31 00:00:00
2023-06-30 00:00:00
2023-07-31 00:00:00
2023-08-31 00:00:00
2023-09-30 00:00:00


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [44]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [50]:
df= pd.DataFrame(lists,columns =['Words','number','number2'])
print(df)

   Words number  number2
0      1    aaa       22
1      2    bbb       25
2      3    ccc       24
